name: Auto

on:
  push:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Job 1
      run: echo "HIIIIII"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - uses: actions/checkout@v2
    - name Job 2
      run: echo "HOOOOOOO"
